# Generated by Django 5.1.7 on 2025-05-19 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_ban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ban',
            options={'verbose_name': 'Бан', 'verbose_name_plural': 'Баны'},
        ),
        migrations.AlterField(
            model_name='ban',
            name='banned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата бана'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='banned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_given', to=settings.AUTH_USER_MODEL, verbose_name='Забанен'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='reason',
            field=models.TextField(verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ban', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterModelTable(
            name='ban',
            table='chat_bans',
        ),
    ]
